- name: Install Nginx
  hosts: web
  become: yes
  tasks:
  - name: Install Nginx in RHEL
    ansible.builtin.dnf:
      name: nginx
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Nginx in ubuntu
    ansible.builtin.apt:
      name: nginx
      state: installed
    when: ansible_os_family == "Debian"