- name: functions
  hosts: local
  connection: local
  tasks:
  - name: using default function
    ansible.builtin.debug:
      msg: "Hello {{ person | default('Ramesh')}}"

  - name: converting string to list
    vars:
      fruits: "apple, banana, orange"
    ansible.builtin.debug:
      msg: "Fruits are {{ fruits | split(',') }}"
  - name: converting dictionary to list
    vars:
      course:
        name: 'ansible'
        duration: '10hrs'
        trainer: 'sivakumar'
    ansible.builtin.debug:
      msg: "course details are {{ course | dict2items }}"
  - name: converting list to dictionary
    vars:
      course:
      - {'key': 'name', 'value': 'ansible'}
      - {'key': 'duration', 'value': '10hrs'}
      - {'key': 'trainer', 'value': 'sivakumar'}
    ansible.builtin.debug:
      msg: "course info {{ course | items2dict }}"
  - name : check ipaddress is valid or not
    vars:
      ip: 192.168.0.1
    ansible.builtin.debug:
      msg: "ip address {{ ip | ansible.utils.ipaddr }}"

  
