- name: Install and setup mysql server
  hosts: mysql
  become: yes
  tasks:
  - name: install mysql server
    ansible.builtin.package:
      name: {{ item }}
      state: installed
    loop:
    - mysql-server
    - PyMySQL
  - name: start and enable mysql server
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: true
  - name: connect to mysql server
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysqldb.manojvaddi.online