- name: Install and start Nginx
  hosts: web
  become: yes
  tasks:
  - name: Install Nginx
    ansible.builtin.service:
      name: nginx
      state: present
  - name: Start Nginx
    ansible.builtin.service:
      name: nginx
      state: started
  - name: enable nginx
    ansible.builtin.service:
      name: nginx
      enabled: true

