- name: Usage of variables
  hosts: local
  connection: local
  vars: # play level variable, can be referred by all plays.
    COURSE: "DEVOPS with AWS"
    DURATION: 120HRS
    TRAINER: "SIVA KUMAR"
  tasks:
  - name: print the variables
    vars: # TASK level variable, can only be referened in this particular task
    COURSE: ANSIBLE
    ansible.builtin.debug: #for debugging and to print the message
      msg: "Course is {{ COURSE }} , Duration {{ DURATION }} and Trainer is {{ TRAINER }}"

  - name: print the variables
    ansible.builtin.debug: #for debugging and to print the message
      msg: "Course is {{ COURSE }} , Duration {{ DURATION }} and Trainer is {{ TRAINER }}"
