- name: usage of variables
  hosts: local
  connection: local
  vars:
    GREET: "Play Variables"
  tasks:
  - name: print play variable
    msg: "the message is {{ GREET }}"
  - name: print task variable
    vars:
      GREET: "Task Variable"
    msg: "the message is {{ GREET }}"