- name: Referance variables from file
  hosts: local
  connection: local
  vars_files:
    - course.yaml
  tasks:
  ansible.builtin.debug:
    msg: "The course is {{ COURSE }}, of duaration {{ DURATION }}, by trainer {{ TRAINER }}"